using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LoLAPI.LoL_Static_Data.v1
{
    class ItemStatsDto
    {
    }
}
FlatArmorMod	int	
FlatAttackSpeedMod	int	
FlatBlockMod	int	
FlatCritChanceMod	int	
FlatCritDamageMod	int	
FlatEXPBonus	int	
FlatHPPoolMod	int	
FlatHPRegenMod	int	
FlatMPPoolMod	int	
FlatMPRegenMod	int	
FlatMagicDamageMod	int	
FlatMovementSpeedMod	int	
FlatPhysicalDamageMod	int	
FlatSpellBlockMod	int	
PercentArmorMod	int	
PercentAttackSpeedMod	int	
PercentBlockMod	int	
PercentCritChanceMod	int	
PercentCritDamageMod	int	
PercentDodgeMod	int	
PercentEXPBonus	int	
PercentHPPoolMod	int	
PercentHPRegenMod	int	
PercentMPPoolMod	int	
PercentMPRegenMod	int	
PercentMagicDamageMod	int	
PercentMovementSpeedMod	int	
PercentPhysicalDamageMod	int	
PercentSpellBlockMod	int	
rFlatArmorModPerLevel	int	
rFlatArmorPenetrationMod	int	
rFlatArmorPenetrationModPerLevel	int	
rFlatCritChanceModPerLevel	int	
rFlatCritDamageModPerLevel	int	
rFlatDodgeMod	int	
rFlatDodgeModPerLevel	int	
rFlatGoldPer10Mod	int	
rFlatHPModPerLevel	int	
rFlatHPRegenModPerLevel	int	
rFlatMPModPerLevel	int	
rFlatMPRegenModPerLevel	int	
rFlatMagicDamageModPerLevel	int	
rFlatMagicPenetrationMod	int	
rFlatMagicPenetrationModPerLevel	int	
rFlatMovementSpeedModPerLevel	int	
rFlatPhysicalDamageModPerLevel	int	
rFlatSpellBlockModPerLevel	int	
rFlatTimeDeadMod	int	
rFlatTimeDeadModPerLevel	int	
rPercentArmorPenetrationMod	int	
rPercentArmorPenetrationModPerLevel	int	
rPercentAttackSpeedModPerLevel	int	
rPercentCooldownMod	int	
rPercentCooldownModPerLevel	int	
rPercentMagicPenetrationMod	int	
rPercentMagicPenetrationModPerLevel	int	
rPercentMovementSpeedModPerLevel	int	
rPercentTimeDeadMod	int	
rPercentTimeDeadModPerLevel	int